#!/bin/bash

curdir="$(pwd)/"

randint=$RANDOM

for file in "$@" ; do
    echo "$curdir$file" >> /tmp/mpv.$randint.playlist
done

mpv --playlist=/tmp/mpv.$randint.playlist

rm  /tmp/mpv.$randint.playlist
